### ISSUE TITLE
Add option to not alter scale but the dimensions only

### ISSUE THREAD

**Issue by 3DManuH** [EleotleCram/MeshTools#3]
Add option to not alter the scale when changing dimensions. So it always stays 1/1/1. Currently workflow is i change dimension and afterwards always have to ctrl-a apply scale.

**Comment by EleotleCram** [comment]
Changing dimensions in Object mode always applies to scale. This is how blender works.
For Mesh Tools I have reverted my changes, so the panel has been removed.

For my new https://github.com/EleotleCram/blender-cad-tools#cad-mesh-dimensions addon, be sure to be in 'EDIT' mode so that the correct panel is showing. Changing values in the _CAD Mesh Dimensions_ panel will never affect scale.
